FROM domjudge/judgehost:latest

# install python3
RUN apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
    python3

## wait wrapper
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.4.0/wait /wait
RUN chmod +x /wait

CMD /wait && /scripts/start.sh
