name: Test Python Solutions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: install flake8
        run: pip install flake8

      # stop the build if there are Python syntax errors or undefined names
      - name: Lint with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # test solutions using test cases
      - name: Test with unittest
        run: python -m unittest tests/test_python_solutions.py

      # lint everything
      - name: Lint with flake8
        run: flake8 . --count --show-source --statistics
